### ISSUE TITLE
Can't render tiles in western hemisphere from command line

### ISSUE THREAD

**Issue by Eiim** [enzet/map-machine#109]
When attempting to render an area using `-b` or `-c`, if the first latitude specified is negative, the argument is interpreted as a flag and the command fails.

Example:
![image](https://user-images.githubusercontent.com/24627058/153106364-0442ead5-2906-4075-89ab-0ffcd8ecf947.png)

Environment: Ubuntu 20.04 in WSL2

BTW: although the contributing guidelines says to add a 'bug' label, I don't believe that's possible as an unprivileged user.

**Comment by enzet** [comment]
Hi @Eiim!

Thank you for reporting this! Unfortunately, I know this issue, the renderer uses standard `argparse` and this is kind of expected behavior. Sorry for not mentioning this for `--coordinates` option, I'll fix this. The solution is indicated in `map-machine render --help` message just for `--boundary-box` option:

```
  -b <lon1>,<lat1>,<lon2>,<lat2>, --boundary-box <lon1>,<lat1>,<lon2>,<lat2>
                        geo boundary box; if the first value is negative,
                        enclose the value with quotes and use space before
                        `-`
```

So, the command should be `map-machine render -b " -84.752045,39.504939,-84.749703,39.508118"`.

I understand this is too counterintuitive and at least this should be in the error message, but I have no idea how to manage this. The alternative approach is to use `=`: `map-machine render -b=-84.752045,39.504939,-84.749703,39.508118`. Do you think this will be more coherent? Maybe I should at least use it in the usage example: `map-machine render -b=2.284,48.860,2.290,48.865`? Or even choose usage example with negative latitude.

> BTW: although the contributing guidelines says to add a 'bug' label, I don't believe that's possible as an unprivileged user.

Oh, my bad. Seems like this is available only for collaborators. I think I should just remove it from the guidelines.

Please let me know if there will be more unclear behavior. Thank you for your interest!

**Comment by enzet** [comment]
@Eiim, could you please take a look at the pull request #110. Do you think it makes things more clear?

**Comment by Eiim** [comment]
As long as using `=` for parameters in that way is done consistently, I think that makes a lot more sense! Thanks!

**Comment by enzet** [comment]
I maintain consistency within a command line, but I'm not sure whether `=` should be used everywhere in the project since spaces are used widely in Python projects and argparse uses them in help message. I think, after all `=` is an alternative for such cases.

**Comment by enzet** [comment]
Hm, I've researched a bit and I think what you mean is

```shell
map-machine render -z 17 -b=-67.7576,-23.0415,-67.7356,-23.0016
```

The error message seems legit to me. I'm not sure if the tool should flip it automatically.

**Comment by enzet** [comment]
Great! You are welcome.

To be honest, it's still challenging to me every time not to mix up latitude and longitude. :)

**Comment by enzet** [comment]
Hi @fredao!

Hope it was helpful.

Yes, Docker was a great idea! Now I have more simple answer on how to install the project.

**Comment by fredao** [comment]
Hi enzet! 
- yes, it was very helpful - Spoiler: ;-) [weeklyOSM](https://weeklyosm.eu/) will report tomorrow with the following text ;-)

"[Enzet](https://www.openstreetmap.org/user/Enzet)" has [mapped](https://www.openstreetmap.org/#map=17/18.98562/-97.31423) the "Large Millimeter Telescope" in Mexico in great detail. He created a "before and after" [animation](https://www.reddit.com/r/openstreetmap/comments/sm4ijh/micromapping_of_large_millimeter_telescope_with/) in color and with roof slopes with his [map-machine](https://github.com/enzet/map-machine) software.

I think you will have to answer more questions starting tomorrow ;-) --- but we have already prepared something for Sunday, 20.02.2022 ;-)

**Comment by enzet** [comment]
> yes, it was very helpful

Nice to hear it!

> [weeklyOSM](https://weeklyosm.eu/) will report tomorrow

Wow! This is great! I didn't expect this attention from the Reddit post. :)

> I think you will have to answer more questions starting tomorrow ;-)

Haha! Now I'm ready! 😅

**Comment by enzet** [comment]
I think this issue is resolved. Feel free to reopen if readme or help message still seems unclear.
