### ISSUE TITLE
Render tourism=camp_pitch

### ISSUE THREAD

**Issue by habi** [enzet/map-machine#144]
It would be great if [`tourism=camp_pitch`](https://wiki.openstreetmap.org/wiki/Tag:tourism=camp_pitch) is rendered, maybe even with its `ref`number if mapped.
A (faint) border could be something appropriate.

Somehow related to me wanting to render [a detailed map of campsites](https://github.com/enzet/map-machine/issues/143)...

**Comment by enzet** [comment]
Good suggestion, thank you!

**Comment by enzet** [comment]
Hi, @habi! I've fixed a bug with the `ref` tag and supported `tourism=camp_pitch` with simple outline if this is an area.

Now it should look like this:

```shell
map-machine render -s 600,400 -c 46.80506/6.71758 -z 19
```

![camp_pitch_19_ref](https://user-images.githubusercontent.com/2399987/197582656-0e8393dd-db8c-4041-ace0-aadd5ee07fda.svg)

```shell
map-machine render -s 600,400 -c 46.80506/6.71758
```

![camp_pitch_18_ref](https://user-images.githubusercontent.com/2399987/197582668-8c4de3c0-1ee3-4404-b511-5178b64a3c40.svg)

## Using an icon

If we want to use an icon, we should specify its minimal zoom level.  I think, 19 is most appropriate.

![camp_pitch_19_icon](https://user-images.githubusercontent.com/2399987/197583792-e1e1de9b-c2ac-45ad-ba86-fd2ba68d29af.svg)

However, due to some limitations of currently used scheme format, for zoom levels 18 and smaller, icons will disapear along with `ref`s.

![camp_pitch_18_icon](https://user-images.githubusercontent.com/2399987/197583777-6b661143-88a9-4f24-a77e-94550764fa5f.svg)

**Comment by habi** [comment]
I think it's very nice that camp pitches are now rendered as faintly visible ways, thanks for implementing this so quickly!
